# Generated by Django 5.2.13 on 2026-04-17 19:08

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("gender", models.CharField(max_length=10)),
                ("gender_probability", models.FloatField()),
                ("sample_size", models.IntegerField()),
                ("age", models.IntegerField()),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("child", "Child"),
                            ("teenager", "Teenager"),
                            ("adult", "Adult"),
                            ("senior", "Senior"),
                        ],
                        max_length=10,
                    ),
                ),
                ("country_id", models.CharField(max_length=5)),
                ("country_probability", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
