# Generated by Django 5.2.13 on 2026-04-23 12:00

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age_group",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="profile",
            table="profiles",
        ),
    ]
